pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: VSBuild@1
  displayName: 'Build solution XBrowserSample/XBrowserSample.sln'
  inputs:
    solution: XBrowserSample/XBrowserSample.sln

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*SeleniumSample*.dll
     
    searchFolder: '$(Build.SourcesDirectory)'
    diagnosticsEnabled: True
